name: sky-kube
type: Skypilot
subtype: kubernetes
config:
  default_cloud: kubernetes
  idle_minutes_to_autostop: 0
assetstores:
  - store_uri: space://assetstores/hf
    pull:
      - mode: default
        config:
          cache_path: /tmp/hf_cache
    push:
      - mode: default
        config: {}
