name: sky-kube
type: Skypilot
subtype: kubernetes
config:
  default_cloud: kubernetes
  idle_minutes_to_autostop: 0
assetstores:
  - store_uri: space://assetstores/env-local
    load:
      - mode: env_local
        config: {}
    push:
      - mode: env_local
        config: {}
  - store_uri: space://assetstores/hf
    load:
      - mode: hf_pull
        config:
          cache_path: /tmp/hf_cache
    push:
      - mode: hf_push
        config: {}
