name: docker-standalone
type: Docker
config:
  defaults:
    pull_policy: "if-not-present"
    env: {}
assetstores:
  - store_uri: space://assetstores/hf/
    pull:
      - mode: default
  # Docker implements file: push only (no pullasset_filestore).
  - store_uri: space://assetstores/file/
    push:
      - mode: default
